### ISSUE TITLE
PrivateMACAddressModeUserSetting

### ISSUE THREAD

**Issue by sphen13** [munkireport/wifi#11]
curious if you had any thoughts on pulling the current value of PrivateMACAddressModeUserSetting for the current SSID from `/Library/Preferences/com.apple.wifi.known-networks.plist`?

ie. `/usr/libexec/PlistBuddy -c "print :wifi.network.ssid.'${SSID}':PrivateMACAddressModeUserSetting" /Library/Preferences/com.apple.wifi.known-networks.plist`

i see currently we are just using system_profiler. It seems apple does not provide this info in there - so that would limit us to a bit of guessing as to what the actual setting is and just check to see if the current WiFi MAC matches our actual MAC.

**Comment by tuxudo** [comment]
It's on my list of things to look into adding :D

**Comment by tuxudo** [comment]
Is now a part of the module with v3.12 :D
