### ISSUE TITLE
Error message after 5.4 to 5.6 update

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/wifi#2]
the wifi page gives me this error: 

`DataTables warning: table id=wifi_known_networks-table - Requested unknown parameter 'channel' for row 0, column 4`

I'm not sure the known networks option works 
`defaults write /Library/Preferences/MunkiReport.plist wifi_known_networks_enabled -bool true`

**Comment by tuxudo** [comment]
The DataTables warning is caused by broken or incomplete migrations. You'll have to manually add that column as defined in the wifi migrations.
