### ISSUE TITLE
wifi – KeyError: '802_11_auth'

### ISSUE THREAD

**Issue by opus-nbonenberger** [munkireport/wifi#8]
On every MunkiReport run, I get this error from the wifi module:

```
    wifi Error: Traceback (most recent call last):
  File "/usr/local/munkireport/scripts/wifi", line 422, in <module>
    main()
  File "/usr/local/munkireport/scripts/wifi", line 410, in main
    result = merge_two_dicts(get_wifi_info(), known_networks)
  File "/usr/local/munkireport/scripts/wifi", line 48, in get_wifi_info
    info["x802_11_auth"] = info["802_11_auth"]
KeyError: '802_11_auth'
WARNING: wifi return code: 1
```

I don't know what the problem is.

**Comment by tuxudo** [comment]
You appear to be running an older version of the module. Anything older than v3.5 (March 2024) will have issues on macOS 14.4+. You need to update your `wifi` module, rebuild the client pkg, and push out the new client pkg to the clients.

**Comment by opus-nbonenberger** [comment]
Yes, you are right. There was a delay from installing the pkg to munkireport-runner using the updated module (it seems).
